[package]
name = "b-reach"
version = "0.1.0"
edition = "2024"

[dependencies]
may_minihttp = "0.1.11"
fxhash = "0.2"
oxc = { version = "0.87", optional = true, features = ["transformer"] }
notify = "8.2.0"
crossbeam-channel = "0.5.15"

[features]
oxc_transformer = ["oxc"]
default = []
